#!/bin/bash
set -eu ;

SSH_DIR="/Users/$(whoami)/.ssh";
CONFIG_FILE="$SSH_DIR/config";
KEYS_DIR="$SSH_DIR/keys";
NEW_HOST_DIR="";

help_info() {
	echo "Register a new host for quick connection (ssh, rsync and scp)";
	echo "	Host will be added to the corresponding config file determined by the '--type' flag";
	echo;
	echo "Usage: $0 [OPTION]... --domain='example.com'";
	echo;
	echo "--domain=(required)";
	echo "	Domain name of the desired host to be added";
	echo "--user=(default: ubuntu)";
	echo "	Username of remote machine";
	echo "--port=(default: 22)";
	echo "	Port of service";
	echo "--key=(optional)";
	echo "	Identity file stored in $KEYS_DIR";
	echo;
}

for arg in "$@"
do
	case $arg in
		-h|--help)
			help_info ;
			exit 0;
		;;
	esac
done;

















