#!/bin/bash
set -eu ;

SSH_DIR="/Users/$(whoami)/.ssh";
CONFIG_FILE="$SSH_DIR/config";
PRORADIS_HOSTS="$SSH_DIR/proradis_hosts";
UBUNTU_HOSTS="$SSH_DIR/ubuntu_hosts";
TELE_HOSTS="$SSH_DIR/tele_hosts";
KEYS_DIR="$SSH_DIR/keys";
NEW_HOST_DIR="";

help_info() {
	echo "Register a new host for quick connection (ssh, rsync and scp)";
	echo "	Host will be added to the corresponding config file determined by the '--type' flag";
	echo;
	echo "Usage: $0 [OPTION]... --domain='example.com'";
	echo;
	echo "--domain=(required)";
	echo "	Domain name of the desired host to be added";
	echo "--type=(default: p)";
	echo "	Type of host to be added: p(proradis), u(ubuntu) or t(tele)";
	echo "--port=(default: 4333)";
	echo "	Port of service";
	echo "--key=(optional)";
	echo "	Identity file stored in $KEYS_DIR";
	echo;
}

for arg in "$@"
do
	case $arg in
		-h|--help)
			help_info ;
			exit 0;
		;;
	esac
done;

















